Online 11463
2gis/MarkerGeneralizationPlugin pull request #44
Opened 2018-02-26 08:08 UTC by RrredHead

ХЗ как это ревьюить. Чекаутите себе -_-

2018-02-27 03:17 UTC, Trufi commented on src/Generalize.js
> +        const retinaFactor = typeof window == 'undefined' ? 1 : window.devicePixelRatio;
А в каких случаях `window === undefined`?

2018-02-27 03:18 UTC, egoroof commented on src/Generalize.js
> +        const retinaFactor = typeof window == 'undefined' ? 1 : window.devicePixelRatio;
в ноде, в воркере)

2018-02-27 03:26 UTC, RrredHead commented on src/Generalize.js
> +        const retinaFactor = typeof window == 'undefined' ? 1 : window.devicePixelRatio;
Перестраховался скорее по привычки. У нас - ни в каких. Но вдруг кто-то когда-то запустит генерализацию на сервере :-)

2018-02-27 03:48 UTC, Trufi commented on src/Generalize.js
> +        const retinaFactor = typeof window == 'undefined' ? 1 : window.devicePixelRatio;
Ясно, правда эта проверка всё равно не спасёт ситуацию, т.к. Leaflet постоянно обращается к `window`, а в General используется `Worker`.

2018-02-27 10:47 UTC, egoroof commented on src/Generalize.js
> +        const markers = new Array(this._otherMarkers.length);
почему не

```js
const markers = [];
...
markers.push(...);
...
```

2018-02-27 10:47 UTC, egoroof commented on src/Generalize.js
> +            markers[i] = newMarker;
```js
markers[i] = {
    groupIndex = this._otherMarkers[i].data.is_advertising ? 0 : 1,
    iconIndex: -1,
    pixelPosition: [pixelPosition.x, pixelPosition.y]
}
```

2018-02-27 11:16 UTC, lastw commented on src/Generalize.js
> +        const self = this;
Оно же нигде не используется. Go eslint с каким-нибудь дефолтным конфигом.

2018-02-27 11:16 UTC, lastw commented on src/Generalize.js
> +    _calculateMarkersClassesIfNeeded: function(_event, zoom = this._map.getZoom()) {
Странная сигнатура функции. Может лучше по месту вызова `event` опускать и `zoom` проставлять?

2018-02-27 11:16 UTC, lastw commented on src/Generalize.js
> +            if (self._map.getZoom() == zoom) {
выше `this`, тут `self`, не надо)

2018-02-27 11:16 UTC, lastw commented on src/Generalize.js
> +            pixelDensity: retinaFactor > 1 ? 2 : 1 // Плотность частиц иконки - 1 или 2
если retinaFactor, например, 3 и выше, что будет? у меня на телефоне 3.4

2018-02-27 11:16 UTC, lastw commented on src/Generalize.js
> +            newMarker.iconIndex = -1;
это точно нужно?

2018-02-27 11:16 UTC, lastw commented on src/Generalize.js
> +            const pixelPosition = this._map.project(this._otherMarkers[i]._latlng, zoom).subtract(topLeftPoint);
либо получаются разные системы координат у маркера и у `bounds`, либо путаница нейминге в относительных и абсолютных баундов. Тут же `(0,0)` в углу экрана? а в `bounds`?

2018-02-28 03:14 UTC, RrredHead commented on src/Generalize.js
> +        const markers = new Array(this._otherMarkers.length);
Очевидно потому, что markers.push это
1. Вызов функции
2. Расширение allocated пространства под массив, что потенциально связано с перемещением блока в памяти, что очень долго.

Крч цель - скорость.

2018-02-28 03:23 UTC, RrredHead commented on src/Generalize.js
> +            pixelDensity: retinaFactor > 1 ? 2 : 1 // Плотность частиц иконки - 1 или 2
Хороший вопрос. Выражение брал из демо-примера. @Trufi подскажи как правильно.

2018-02-28 03:24 UTC, RrredHead commented on src/Generalize.js
> +            newMarker.iconIndex = -1;
Да

2018-02-28 03:41 UTC, RrredHead commented on src/Generalize.js
> +            const pixelPosition = this._map.project(this._otherMarkers[i]._latlng, zoom).subtract(topLeftPoint);
Разобрались

2018-02-28 04:00 UTC, Trufi requested changes

2018-02-28 04:00 UTC, Trufi commented on .editorconfig
> +indent_style = tab
Зачем тут что-то про Makefile?

2018-02-28 04:00 UTC, Trufi commented on src/Generalize.js
> +         * 1.2 Если попадаем в рамки границ, для которых уже произведена генерализация, то ничего не делаем
Почему не надо заново проводить генерализацию? При увеличении зума старые маркера становятся более рассредоточенными и для новых может появиться место, в этом случае, кажется, мы должны их показать.

2018-02-28 04:00 UTC, Trufi commented on src/Generalize.js
> +        const calcedBounds = this._zoomStat[zoom].bounds; // Это "старые" границы, которые были генерализированы
Кажется, в английском нет слова "calced", есть "calculated".

2018-02-28 04:00 UTC, Trufi commented on src/Generalize.js
> +        const atlasSpritesImulation = levels.map((level) => ({
Может "Emulation"?

2018-02-28 04:00 UTC, Trufi commented on package.json
> +    "build": "NODE_ENV=production webpack"
Для чего прокидывать `NODE_ENV=production`?
Вроде бы, это нигде не используется у тебя, кроме того, ломают сборку под винду.

2018-02-28 04:00 UTC, Trufi commented on package.json
> +    "babel-preset-env": "^1.6.1"
По какому принципу `wepback` попадает в devDependencies, a babel — нет?

2018-02-28 04:00 UTC, Trufi commented on src/Generalize.js
> +        const priorityGroups = levels.map((level) => ({
`levels` могут меняться в процессе работы плагина? Если нет, то почему бы `priorityGroups` и  `atlasSpritesImulation ` заранее один раз не подготовить?

2018-02-28 04:00 UTC, Trufi commented on src/Generalize.js
> +        const markers = new Array(this._otherMarkers.length);
Не лучше ли было, при добавление маркеров в плагин, сразу переводить их в нужный формат, чтобы потом не делать этого перед каждым вызовом генерала?

2018-02-28 04:03 UTC, egoroof commented on package.json
> +    "build": "NODE_ENV=production webpack"
тут можно просто сделать `webpack -p`

2018-02-28 06:46 UTC, RrredHead commented on src/Generalize.js
> +        const markers = new Array(this._otherMarkers.length);
Сделал оптимизацию.

2018-02-28 06:48 UTC, RrredHead commented on .editorconfig
> +indent_style = tab
Это стандартный шаблон. Завтра ко-то захочет добавить make.  Why not?

2018-02-28 06:49 UTC, RrredHead commented on src/Generalize.js
> +         * 1.2 Если попадаем в рамки границ, для которых уже произведена генерализация, то ничего не делаем
Границы генерализации для каждого зума свои, смотри по коду ниже.

2018-02-28 06:53 UTC, RrredHead commented on package.json
> +    "babel-preset-env": "^1.6.1"
Случайность, кажется. Поправил

2018-02-28 06:53 UTC, RrredHead commented on package.json
> +    "build": "NODE_ENV=production webpack"
Поправил

2018-02-28 06:54 UTC, RrredHead commented on src/Generalize.js
> +        const priorityGroups = levels.map((level) => ({
Levels меняются в зависимости от зума.
В любом случае, это уже микрооптимизация, там всего-то 3-5 элементов.

2018-02-28 07:13 UTC, Trufi commented on src/Generalize.js
> +            pixelDensity: retinaFactor > 1 ? 2 : 1 // Плотность частиц иконки - 1 или 2
Потому что в демке используется картинки маркеров только для ретина факторов 1 и 2 (больше было лень добавлять). Здесь можно попробовать сделать и больше.

2018-02-28 07:15 UTC, Trufi commented on .editorconfig
> +indent_style = tab
По той же причине, почему мы не добавляем всякие другие сущности в проекты, например, тут нет файлов `tsconfig.json`, `tslint.json`, а вдруг кто-то захочет добавить тайпскрипт?

2018-02-28 07:18 UTC, Trufi commented on src/Generalize.js
> +         * 1.2 Если попадаем в рамки границ, для которых уже произведена генерализация, то ничего не делаем
Понял. Не совсем очевидный момент :)

2018-02-28 07:21 UTC, Trufi approved these changes

2018-02-28 07:23 UTC, Trufi commented
Ещё заметил, что ты добавил `package-lock.json`, может не надо?

2018-02-28 07:27 UTC, Trufi commented
1. В названиях веток и пулл реквестах открытого проекта фигурируют внутренние номера тасок из jira, без нормального описания на github.
2. Код проекта чрезмерно завязан на логику онлайна.

Давайте сделаем его приватным и перенесем на гитлаб? Довольно стрёмно иметь такое в списке репозиториев компании.

Что думаете @RrredHead @lastw?

2018-02-28 07:44 UTC, RrredHead commented
@Trufi 
> Ещё заметил, что ты добавил package-lock.json, может не надо?

Why not?

> Код проекта чрезмерно завязан на логику онлайна

Или перетащим просто в онлайн. В целом это можно, но я бы предпочёл это сделать чуть позднее, чтобы не усложнять текущую задачу.

> ... без нормального описания на github

My bad, надо бы добавить описание в PR. Сделаю.

2018-02-28 07:56 UTC, lastw approved these changes

2018-02-28 09:21 UTC, Trufi commented
>> Ещё заметил, что ты добавил package-lock.json, может не надо?

> Why not?

Кто-то всё ещё пользуется старым npm, кто-то yarn. В итоге этот файл будет не у всех обновляться, а если на вашем билд сервере не используется npm версии 5, то он вообще бесполезен.

2018-02-28 09:50 UTC, lastw commented
> А если на вашем билд сервере не используется npm версии 5, то он вообще бесполезен.

Тут `dist` билдим руками. Считай файл `package-lock.json` снапшотом node_modules того, кто этот файл последним обновлял, и ничем больше. Файл сам по себе не создаёт проблем, но может потом некоторые проблемы решить.

и почему в 2gis/general закоммитили yarn.lock? :D

2018-02-28 11:04 UTC, Trufi commented
> и почему в 2gis/general закоммитили yarn.lock? :D

На волне хайпа :) Сейчас бы так не сделали.
Окей, скорее всего этим плагином будете пользоваться только вы, поэтому вам решать как удобнее.

2018-02-28 18:31 UTC, ktoto commented on src/Generalize.js
> +        );
`const newLatLngBounds = this._map.getBounds();` вроде заменяет два вызова.

Ты же ту по факту баунд экрана считаешь?

2018-02-28 18:31 UTC, ktoto commented on src/Generalize.js
> +                    .subtract(topLeftPoint);
const pixelPosition = this._map.latLngToLayerPoint(this._zoomStat[zoom].markers[i]._latlng);

2018-02-28 18:31 UTC, ktoto commented on src/Generalize.js
> +            const pixelPosition = this._map.project(this._otherMarkers[i]._latlng, zoom).subtract(topLeftPoint);
const pixelPosition = this._map.latLngToLayerPoint(this._otherMarkers[i]._latlng);

2018-02-28 18:31 UTC, ktoto commented on src/Generalize.js
> +        bufferPart: 0.5,
Ну вот зачем ломать обратную совместимость? А вдруг Фламп еще плагин использует. Или еще кто...

2018-03-05 02:53 UTC, RrredHead commented on src/Generalize.js
> +        );
Да, но на конкретном зуме. Поэтому this._map.getBounds() не подходит

2018-03-05 02:56 UTC, RrredHead commented on src/Generalize.js
> +        bufferPart: 0.5,
Я повысил версию с 0.0.2 или что-то такое до 1.0.0. Согласно semver это breaking changes. Если фламп или кто-то там ещё сидит на посленем коммите мастера - это их дело, ИМХО. К тому же этот параметр теперь работает немного по-другому. Для пользователя конечно разницы нет, но смысловая нагрузка поменялась.

2018-03-05 02:57 UTC, RrredHead commented on src/Generalize.js
> +            const pixelPosition = this._map.project(this._otherMarkers[i]._latlng, zoom).subtract(topLeftPoint);
Снова не учтён зум.

2018-03-05 02:59 UTC, RrredHead commented on src/Generalize.js
> +        bufferPart: 0.5,
И кстати если фламп(или кто-то ещё) использует этот плагин, то им придётся править конфиги :-)

2018-03-19 04:57 UTC, merged